title: Micayla Fong Portfolio
description: Personal portfolio site
baseurl: "" # leave empty unless using a project page
url: "https://mdfong35.github.io"

theme: jekyll-theme-minimal

markdown: kramdown
